server:
    port: ${svport}
spring:
    datasource:
        password: ${dbpassword}
        url: ${dburl}
        username: ${dbuser}
    jpa: 
        hibernate:
            ddl-auto: update
            database-platform: ${dbplatform}
    liquibase:
        change-log: classpath:db/changelog/changelog-master.yml
        enabled: true